"""esquema inicial de LibraCargo

Revision ID: 0001
Revises: 
Create Date: 2026-08-18 12:59:02.983709
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=120), nullable=True),
    sa.Column('entidad', sa.String(length=60), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.Enum('alta', 'modificacion', 'baja', name='accion_auditoria'), nullable=False),
    sa.Column('datos_antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditoria_entidad', 'auditoria', ['entidad', 'entidad_id'], unique=False)
    op.create_index('ix_auditoria_ts', 'auditoria', ['ts'], unique=False)
    op.create_index('ix_auditoria_usuario', 'auditoria', ['usuario_id'], unique=False)
    op.create_table('localidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('provincia', sa.String(length=60), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_localidades_nombre')
    )
    op.create_table('razones_sociales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.Column('condicion_iva', sa.Enum('responsable_inscripto', 'monotributo', 'exento', 'consumidor_final', 'no_categorizado', name='condicion_iva'), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('codigo_legado', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_legado', name='uq_razones_sociales_codigo_legado'),
    sa.UniqueConstraint('nombre', name='uq_razones_sociales_nombre')
    )
    op.create_table('terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=120), nullable=False),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.Column('condicion_iva', sa.Enum('responsable_inscripto', 'monotributo', 'exento', 'consumidor_final', 'no_categorizado', name='condicion_iva'), nullable=False),
    sa.Column('es_cliente', sa.Boolean(), nullable=False),
    sa.Column('es_fletero', sa.Boolean(), nullable=False),
    sa.Column('es_proveedor', sa.Boolean(), nullable=False),
    sa.Column('direccion', sa.String(length=160), nullable=True),
    sa.Column('codigo_postal', sa.String(length=12), nullable=True),
    sa.Column('localidad', sa.String(length=80), nullable=True),
    sa.Column('provincia', sa.String(length=60), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('celular', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contacto', sa.String(length=80), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('origen_legado', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.CheckConstraint('es_cliente OR es_fletero OR es_proveedor', name='ck_terceros_al_menos_un_rol'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_terceros_cuit', 'terceros', ['cuit'], unique=False)
    op.create_index('ix_terceros_es_cliente', 'terceros', ['es_cliente'], unique=False, postgresql_where='es_cliente')
    op.create_index('ix_terceros_es_fletero', 'terceros', ['es_fletero'], unique=False, postgresql_where='es_fletero')
    op.create_index('ix_terceros_origen_legado', 'terceros', ['origen_legado'], unique=True)
    op.create_index('ix_terceros_razon_social', 'terceros', ['razon_social'], unique=False)
    op.create_table('tipos_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('unidad_default', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_tipos_carga_nombre')
    )
    op.create_table('choferes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('fletero_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('origen_legado', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fletero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_choferes_fletero', 'choferes', ['fletero_id'], unique=False)
    op.create_index('ix_choferes_nombre', 'choferes', ['nombre'], unique=False)
    op.create_index('ix_choferes_origen_legado', 'choferes', ['origen_legado'], unique=True)
    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('factura_a', 'factura_b', 'factura_c', 'nota_credito_a', 'nota_credito_b', 'nota_credito_c', name='tipo_comprobante'), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('neto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('origen_legado', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('neto >= 0 AND iva >= 0 AND total >= 0', name='ck_comprobantes_signos'),
    sa.ForeignKeyConstraint(['cliente_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['razon_social_id'], ['razones_sociales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razon_social_id', 'tipo', 'punto_venta', 'numero', name='uq_comprobantes_numeracion')
    )
    op.create_index('ix_comprobantes_cliente_fecha', 'comprobantes', ['cliente_id', 'fecha'], unique=False)
    op.create_index('ix_comprobantes_fecha', 'comprobantes', ['fecha'], unique=False)
    op.create_index('ix_comprobantes_origen_legado', 'comprobantes', ['origen_legado'], unique=True)
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'egreso', name='tipo_movimiento_caja'), nullable=False),
    sa.Column('concepto', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('medio_pago', sa.Enum('efectivo', 'transferencia', 'cheque', 'otro', name='medio_pago'), nullable=False),
    sa.Column('recibo', sa.String(length=30), nullable=True),
    sa.Column('origen_legado', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('importe > 0', name='ck_caja_importe_positivo'),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_caja_fecha', 'movimientos_caja', ['fecha'], unique=False)
    op.create_index('ix_caja_origen_legado', 'movimientos_caja', ['origen_legado'], unique=True)
    op.create_index('ix_caja_tercero_fecha', 'movimientos_caja', ['tercero_id', 'fecha'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patente_chasis', sa.String(length=12), nullable=False),
    sa.Column('patente_acoplado', sa.String(length=12), nullable=True),
    sa.Column('fletero_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fletero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patente_chasis', 'patente_acoplado', name='uq_vehiculos_equipo')
    )
    op.create_index('ix_vehiculos_fletero', 'vehiculos', ['fletero_id'], unique=False)
    op.create_table('ordenes_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('origen_id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.Column('fletero_id', sa.Integer(), nullable=True),
    sa.Column('chofer_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_carga_id', sa.Integer(), nullable=True),
    sa.Column('remito', sa.String(length=30), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad_legado', sa.String(length=40), nullable=True),
    sa.Column('tarifa', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('alicuota_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comision', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'facturada', 'anulada', name='estado_orden'), nullable=False),
    sa.Column('razon_social_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.Column('origen_legado', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.CheckConstraint("(estado = 'facturada' AND comprobante_id IS NOT NULL) OR (estado <> 'facturada' AND comprobante_id IS NULL)", name='ck_ordenes_facturada_con_comprobante'),
    sa.CheckConstraint('alicuota_iva >= 0 AND alicuota_iva <= 100', name='ck_ordenes_alicuota'),
    sa.CheckConstraint('origen_id <> destino_id', name='ck_ordenes_origen_distinto_destino'),
    sa.CheckConstraint('tarifa >= 0 AND total >= 0', name='ck_ordenes_importes_no_negativos'),
    sa.ForeignKeyConstraint(['chofer_id'], ['choferes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destino_id'], ['localidades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fletero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origen_id'], ['localidades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['razon_social_id'], ['razones_sociales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_carga_id'], ['tipos_carga.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ordenes_cliente_fecha', 'ordenes_carga', ['cliente_id', 'fecha'], unique=False)
    op.create_index('ix_ordenes_comprobante', 'ordenes_carga', ['comprobante_id'], unique=False)
    op.create_index('ix_ordenes_estado', 'ordenes_carga', ['estado'], unique=False)
    op.create_index('ix_ordenes_fecha', 'ordenes_carga', ['fecha'], unique=False)
    op.create_index('ix_ordenes_fletero_fecha', 'ordenes_carga', ['fletero_id', 'fecha'], unique=False)
    op.create_index('ix_ordenes_origen_legado', 'ordenes_carga', ['origen_legado'], unique=True)
    op.create_index('ix_ordenes_remito', 'ordenes_carga', ['remito'], unique=False)
    op.create_table('movimientos_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tercero_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('cliente', 'fletero', 'proveedor', name='rol_cuenta'), nullable=False),
    sa.Column('concepto', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('debe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('haber', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.Column('movimiento_caja_id', sa.Integer(), nullable=True),
    sa.Column('origen_legado', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(debe > 0 AND haber = 0) OR (haber > 0 AND debe = 0)', name='ck_cuenta_debe_o_haber'),
    sa.CheckConstraint('debe >= 0 AND haber >= 0', name='ck_cuenta_signos'),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movimiento_caja_id'], ['movimientos_caja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_carga.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cuenta_caja', 'movimientos_cuenta', ['movimiento_caja_id'], unique=False)
    op.create_index('ix_cuenta_comprobante', 'movimientos_cuenta', ['comprobante_id'], unique=False)
    op.create_index('ix_cuenta_orden', 'movimientos_cuenta', ['orden_id'], unique=False)
    op.create_index('ix_cuenta_origen_legado', 'movimientos_cuenta', ['origen_legado'], unique=True)
    op.create_index('ix_cuenta_saldo', 'movimientos_cuenta', ['tercero_id', 'rol', 'fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cuenta_saldo', table_name='movimientos_cuenta')
    op.drop_index('ix_cuenta_origen_legado', table_name='movimientos_cuenta')
    op.drop_index('ix_cuenta_orden', table_name='movimientos_cuenta')
    op.drop_index('ix_cuenta_comprobante', table_name='movimientos_cuenta')
    op.drop_index('ix_cuenta_caja', table_name='movimientos_cuenta')
    op.drop_table('movimientos_cuenta')
    op.drop_index('ix_ordenes_remito', table_name='ordenes_carga')
    op.drop_index('ix_ordenes_origen_legado', table_name='ordenes_carga')
    op.drop_index('ix_ordenes_fletero_fecha', table_name='ordenes_carga')
    op.drop_index('ix_ordenes_fecha', table_name='ordenes_carga')
    op.drop_index('ix_ordenes_estado', table_name='ordenes_carga')
    op.drop_index('ix_ordenes_comprobante', table_name='ordenes_carga')
    op.drop_index('ix_ordenes_cliente_fecha', table_name='ordenes_carga')
    op.drop_table('ordenes_carga')
    op.drop_index('ix_vehiculos_fletero', table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index('ix_caja_tercero_fecha', table_name='movimientos_caja')
    op.drop_index('ix_caja_origen_legado', table_name='movimientos_caja')
    op.drop_index('ix_caja_fecha', table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index('ix_comprobantes_origen_legado', table_name='comprobantes')
    op.drop_index('ix_comprobantes_fecha', table_name='comprobantes')
    op.drop_index('ix_comprobantes_cliente_fecha', table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_index('ix_choferes_origen_legado', table_name='choferes')
    op.drop_index('ix_choferes_nombre', table_name='choferes')
    op.drop_index('ix_choferes_fletero', table_name='choferes')
    op.drop_table('choferes')
    op.drop_table('tipos_carga')
    op.drop_index('ix_terceros_razon_social', table_name='terceros')
    op.drop_index('ix_terceros_origen_legado', table_name='terceros')
    op.drop_index('ix_terceros_es_fletero', table_name='terceros', postgresql_where='es_fletero')
    op.drop_index('ix_terceros_es_cliente', table_name='terceros', postgresql_where='es_cliente')
    op.drop_index('ix_terceros_cuit', table_name='terceros')
    op.drop_table('terceros')
    op.drop_table('razones_sociales')
    op.drop_table('localidades')
    op.drop_index('ix_auditoria_usuario', table_name='auditoria')
    op.drop_index('ix_auditoria_ts', table_name='auditoria')
    op.drop_index('ix_auditoria_entidad', table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
    # Alembic autogenera el DROP de las tablas pero **no el de los tipos ENUM**.
    # Sin esto el downgrade deja los 7 tipos huérfanos y el siguiente upgrade
    # muere con `DuplicateObject: type "accion_auditoria" already exists`: la
    # migración parece reversible y no lo es. Verificado rompiéndolo.
    for tipo in (
        "accion_auditoria",
        "condicion_iva",
        "estado_orden",
        "medio_pago",
        "rol_cuenta",
        "tipo_comprobante",
        "tipo_movimiento_caja",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {tipo}"))

